const MILESTONES = [
  { id: 1, name: 'Zoho CRM Configuration' },
  { id: 2, name: 'Zoho CRM Workflows, Automations & Meta Ads Integration' },
  { id: 3, name: 'Zoho Desk Setup' },
  { id: 4, name: 'Zoho CRM Integration with Mazad Platform' },
  { id: 5, name: 'Zoho Marketing Automation' },
  { id: 6, name: 'Zoho SalesIQ Setup' },
  { id: 7, name: 'Zoho Books Integration' },
  { id: 8, name: 'Zoho Analytics' },
  { id: 9, name: 'UAT & Go-Live' },
];

const RAW_TASKS = [
  [1,1,"Configure Zoho CRM organization settings"],
  [2,1,"Create user roles, profiles, permission sets, and organizational hierarchy"],
  [3,1,"Configure standard CRM modules: Leads, Contacts, Accounts, Deals, Activities, Tasks, Calls, and Meetings"],
  [4,1,"Design and implement custom modules for Auction Listings, Bids, Buyers, Sellers, Auction Transactions"],
  [5,1,"Configure custom fields, layouts, related lists, validation rules, picklists, and lookup relationships"],
  [6,1,"Establish relationships between customers, auction listings, bids, and transactions"],
  [7,1,"Configure page layouts and user interface elements for sales, operations, and management teams"],
  [8,1,"Implement duplicate detection rules and data validation mechanisms"],
  [9,1,"Configure Zoho CRM organization"],
  [10,1,"Configure standard CRM modules"],
  [11,1,"Implement custom auction modules"],
  [12,1,"Configure user roles, profiles, and security"],
  [13,1,"Configure custom fields and layouts"],
  [14,1,"Develop reports and dashboards"],
  [15,1,"Configure email templates"],
  [16,2,"Design and implement workflow rules for routine CRM activities"],
  [17,2,"Configure lead assignment rules"],
  [18,2,"Implement workflow automations for seller onboarding, customer verification, auction listing approvals"],
  [19,2,"Configure approval processes for premium seller verification, auction listing approvals, high-value transactions"],
  [20,2,"Create automated task generation and reminder notifications"],
  [21,2,"Configure email notifications and customer communication workflows"],
  [22,2,"Implement escalation rules for delayed approvals, unattended customer requests, overdue activities"],
  [23,2,"Integrate Meta Ads (Facebook and Instagram) with Zoho CRM to capture Lead Ads"],
  [24,2,"Configure lead mapping, source attribution, and campaign tracking"],
  [25,2,"Configure Blueprint processes where applicable"],
  [26,2,"Develop workflow automation for customer lifecycle stages"],
  [27,2,"Configure scheduled workflows and custom functions for recurring operational activities"],
  [28,2,"Configure workflow automation rules"],
  [29,2,"Implement lead assignment automation"],
  [30,2,"Configure approval processes"],
  [31,2,"Set up Meta Ads integration and reports"],
  [32,2,"Implement Blueprint processes where applicable"],
  [33,2,"Configure automated notifications and reminders"],
  [34,2,"Implement customer communication workflows"],
  [35,2,"Configure escalation rules"],
  [36,2,"Complete workflow testing and validation"],
  [37,3,"Configure Zoho Desk organization settings"],
  [38,3,"Create Buyer Support, Seller Support, Auction Operations, Payments, Verification & KYC departments"],
  [39,3,"Configure agent profiles, roles, permissions, and department access"],
  [40,3,"Set up ticket intake channels including email, web forms, APIs, and other supported channels"],
  [41,3,"Design ticket layouts, custom fields, and ticket categories"],
  [42,3,"Configure ticket assignment rules and automation"],
  [43,3,"Implement SLAs, business hours, escalation rules, and notification workflows"],
  [44,3,"Configure ticket lifecycle statuses, priorities, and resolution workflows"],
  [45,3,"Develop knowledge base articles, FAQs, user guides, auction policies, and troubleshooting documentation"],
  [46,3,"Configure customer support portal"],
  [47,3,"Integrate Zoho Desk with Zoho CRM"],
  [48,3,"Configure dashboards and reports for ticket volumes, response times, SLA compliance"],
  [49,3,"Configure Zoho Desk organization"],
  [50,3,"Establish departments, roles, and agent permissions"],
  [51,3,"Configure ticket channels and routing"],
  [52,3,"Implement ticket layouts, custom fields, and categories"],
  [53,3,"Configure SLA policies and escalation workflows"],
  [54,3,"Implement ticket assignment and automation rules"],
  [55,3,"Configure customer support portal"],
  [56,3,"Develop knowledge base"],
  [57,3,"Complete Zoho CRM and Zoho Desk integration"],
  [58,3,"Configure support dashboards and reports"],
  [59,4,"Conduct integration workshop to identify required data exchange"],
  [60,4,"Review Mazad API documentation and authentication mechanisms"],
  [61,4,"Design secure, scalable, and reliable integration architecture using REST APIs and webhooks"],
  [62,4,"Develop API integrations for customer information"],
  [63,4,"Configure automatic creation or update of CRM customer records"],
  [64,4,"Synchronize auction listings into Zoho CRM"],
  [65,4,"Implement bid synchronization"],
  [66,4,"Configure related record associations between customers, listings, bids, transactions"],
  [67,4,"Implement synchronization of auction lifecycle events"],
  [68,4,"Develop integration workflows for customer activities and interactions"],
  [69,4,"Configure exception handling, logging, and monitoring"],
  [70,4,"Implement secure API integration between Mazad and Zoho CRM"],
  [71,4,"Implement user registration and profile synchronization"],
  [72,4,"Implement auction listing synchronization"],
  [73,4,"Implement bid and bidding activity synchronization"],
  [74,4,"Prepare data mapping and field transformation documentation"],
  [75,4,"Configure integration monitoring and error logging"],
  [76,5,"Configure Zoho Marketing Automation organization settings, branding, sender domains, SPF, DKIM, DMARC"],
  [77,5,"Integrate Zoho Marketing Automation with Zoho CRM"],
  [78,5,"Design and configure audience segments"],
  [79,5,"Configure marketing journeys for onboarding, verification reminders, auction participation"],
  [80,5,"Design and configure branded email templates"],
  [81,5,"Configure lead scoring and engagement scoring models"],
  [82,5,"Implement subscription management, consent preferences, and unsubscribe mechanisms"],
  [83,5,"Configure campaign tracking, email performance monitoring, and engagement analytics"],
  [84,5,"Set up dashboards and reports for campaign performance, audience growth"],
  [85,5,"Configure Zoho Marketing Automation organization"],
  [86,5,"Complete Zoho CRM integration"],
  [87,5,"Configure customer segments and audience lists"],
  [88,5,"Implement automated customer journeys"],
  [89,5,"Create branded email templates"],
  [90,5,"Configure campaign performance dashboards and reports"],
  [91,6,"Configure Zoho SalesIQ organization, branding, user roles, departments, operating hours"],
  [92,6,"Install and configure SalesIQ tracking code on the Mazad website and web application"],
  [93,6,"Configure live chat channels and department routing"],
  [94,6,"Design customized chat widgets aligned with Mazad branding"],
  [95,6,"Configure proactive chat triggers based on visitor behavior"],
  [96,6,"Set up visitor segmentation"],
  [97,6,"Integrate Zoho SalesIQ with Zoho CRM"],
  [98,6,"Integrate Zoho SalesIQ with Zoho Desk"],
  [99,6,"Configure chat routing rules, canned responses, notifications, and agent availability"],
  [100,6,"Set up chatbot capabilities where applicable"],
  [101,6,"Configure dashboards and reports for visitor traffic, chat volumes, response times"],
  [102,6,"Configure Zoho SalesIQ organization"],
  [103,6,"Deploy live chat widget on the Mazad platform"],
  [104,6,"Configure visitor tracking and behavioral analytics"],
  [105,6,"Configure chat routing rules and departments"],
  [106,6,"Implement proactive chat triggers and visitor segmentation"],
  [107,6,"Complete Zoho CRM and Zoho Desk integrations"],
  [108,7,"Configure Zoho CRM and Zoho Books integration"],
  [109,7,"Map CRM customers, auction transactions, seller information, and chargeable services to Zoho Books"],
  [110,7,"Configure automated invoice generation for successful auction completion, premium listing purchases"],
  [111,7,"Design branded invoice templates"],
  [112,7,"Configure tax settings, currencies, payment terms, and invoice numbering sequences"],
  [113,7,"Enable invoice status synchronization between Zoho Books and Zoho CRM"],
  [114,7,"Configure workflows and notifications for invoices, payment reminders, overdue balances"],
  [115,7,"Implement error handling and validation for invoice data synchronization"],
  [116,7,"Configure reports and dashboards for invoice generation, payment status"],
  [117,7,"Configure Zoho CRM and Zoho Books integration"],
  [118,7,"Implement customer and financial data synchronization"],
  [119,7,"Implement automated invoice generation workflows"],
  [120,7,"Create branded invoice templates"],
  [121,7,"Configure tax, currency, and payment terms"],
  [122,7,"Implement invoice status synchronization"],
  [123,7,"Configure invoice reports and dashboards"],
  [124,8,"Configure Zoho Analytics workspace"],
  [125,8,"Establish secure connections with Zoho CRM, Zoho Desk, Zoho Marketing Automation, Zoho SalesIQ, Zoho Books"],
  [126,8,"Design unified data model combining customer, auction, bidding, support, marketing, and financial data"],
  [127,8,"Develop executive dashboards"],
  [128,8,"Configure interactive reports, filters, and drill-down capabilities"],
  [129,8,"Configure scheduled data synchronization"],
  [130,8,"Set up automated report scheduling and dashboard sharing"],
  [131,8,"Validate data accuracy and perform end-to-end testing"],
  [132,8,"Configure Zoho Analytics workspace"],
  [133,8,"Complete data integration with Zoho applications and Mazad platform"],
  [134,8,"Develop executive dashboards and business reports"],
  [135,8,"Configure interactive dashboards with filters and drill-downs"],
  [136,8,"Configure automated data synchronization and report scheduling"],
  [137,9,"Prepare comprehensive UAT plan"],
  [138,9,"Execute end-to-end testing with Mazad business users"],
  [139,9,"Record, prioritize, and resolve UAT issues"],
  [140,9,"Perform regression testing after fixes"],
  [141,9,"Validate data synchronization and integrations across all Zoho applications and Mazad platform"],
  [142,9,"Prepare production environment through configuration reviews, user access verification, deployment readiness"],
  [143,9,"Conduct administrator and end-user training"],
  [144,9,"Provide necessary documentation for ongoing system administration"],
  [145,9,"Execute production go-live"],
  [146,9,"Monitor system performance and provide post-deployment support"],
  [147,9,"Address stabilization-period issues before formal project handover"],
  [148,9,"Complete UAT plan and execution"],
  [149,9,"Obtain UAT sign-off"],
  [150,9,"Complete issue resolution and regression testing"],
  [151,9,"Complete production deployment"],
  [152,9,"Complete user and administrator training"],
  [153,9,"Provide go-live support and stabilization"],
  [154,9,"Complete project handover documentation"],
];

const ms_map = Object.fromEntries(MILESTONES.map(m => [m.id, m.name]));

const SEED_TASKS = RAW_TASKS.map(([id, msId, task]) => ({
  taskId: id,
  milestoneId: msId,
  milestone: ms_map[msId],
  task,
  status: 'Not Started',
  priority: 'Medium',
  startDate: null,
  dueDate: null,
  notes: '',
  reminderDate: null,
  reminderEmail: '',
  reminderSent: false,
  reminderNote: '',
}));

module.exports = { SEED_TASKS };
